/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package AverageJoes

import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatestplus.junit

//@RunWith(classOf[junit])
class LibrarySuite extends FunSuite {
  test("someLibraryMethod is always true") {
    def library = new Library()
    assert(library.someLibraryMethod)
  }
}
